### ISSUE TITLE
applications-editor

### ISSUE THREAD

**Issue by laopeng2021** [dafreels/metalus-api#98] opened 2020-11-02 08:00 UTC
Is applications-editor under development?
Look at this menu, it is commented out.

When is the expected application-editor menu available? Thank you

<a mat-menu-item [routerLink]="['/']" routerLinkActive="active">
      <mat-icon color="primary">home</mat-icon>
      <span class="spacer">Home</span>
  </a>
  
  
  
  
  
  
  
  <a mat-menu-item [routerLink]="['/pipelines-editor']"

**Comment by dafreels** [comment] 2020-11-20 12:05
Duplicate of #5

**Closed** 2020-11-20 12:05 UTC
